# Generated by Django 2.2 on 2023-03-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
