# Generated by Django 2.2 on 2023-03-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_images_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
